<?php
/**
 * @file
 * Code for the Vejlebib Views and Panels feature.
 */

include_once 'vejlebib_views_panels.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Tells panels where to find plugins.
 */
function vejlebib_views_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_menu_alter().
 */
function vejlebib_views_panels_menu_alter(&$items) {
  // Overrid the page callback from ding_app_variables to instead return
  // carouesels from our own frontpage.
  $items['ding/variables']['page callback'] = 'vejlebib_variables_display';
}

/**
 * Page callback for ding/variables.
 */
function vejlebib_variables_display() {
  // Let ding_app_variables handle everything other than carousels.
  $configs = ding_app_variables_display();

  $ding_frontpage = page_manager_get_page_cache('page-vejlebib_frontpage');
  $handler = reset($ding_frontpage->handlers);
  $display = panels_panel_context_get_display($handler);
  $carousels = [];
  foreach ($display->content as &$pane) {
    if ($pane->type == 'carousel' && $pane->subtype == 'carousel') {
      $carousels[] = ['carousel' => $pane->configuration];
    }
  }

  // Override the carousels from ding_app_variables.
  $configs['carousels'] = [$carousels];

  return $configs;
}

/**
 * Implements hook_block_info().
 */
function vejlebib_views_panels_block_info() {
  $blocks = array();

  $blocks['vejlebib-nav-helpers'] = array(
    'info' => t('Vejlebib nav help links'),
    'cache' => '', // What type cache to use?
  );

  return $blocks;
}

/**
 * Implements hook_theme().
 */
function vejlebib_views_panels_theme($existing, $type, $theme, $path) {
  return array(
    'vejlebib_views_panels_ding_userinfo' => array(
      'variables' => array('name' => NULL, 'pickup' => array(), 'reservation' => array(), 'debt' => array(), 'loan' => array(), 'bookmark' => array()),
      'template' => 'vejlebib_views_panels_ding_userinfo',
      'path' => $path . '/templates',
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function vejlebib_views_panels_block_view($delta) {
  $block = array();
  $content = array();
  global $user;

  switch ($delta) {
    case 'vejlebib-nav-helpers':
      // Nav helper links markup
      $content[] = array(
          '#type' => 'markup',
          '#markup' => '<ul class="nav-helpers"><li><a class="english" href="/in-english">English</a></li><li><a class="read" href="http://adgangforalle.dk">Læs op</a></li><li><a class="facebook" href="https://www.facebook.com/vejlebibliotekerne" target="_blank">Facebook</a></li></ul>',
        );
      // Temporary disabled print menu:
      /*<li><a class="print" href="javascript:window.print();">Print</a></li>*/
      // Define the block.
      $block['content'] = $content;
      break;
  }

  return $block;
}
