<?php

/**
 * @file
 * Ding SEO module file.
 */

 /**
 * Implements hook_menu().
 */
function ding_seo_menu() {
  $items = array();

  $items['admin/config/ding/ding_seo'] = array(
    'title' => 'Ding SEO',
    'description' => 'Configure the SEO module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_seo_admin_settings'),
    'access arguments' => array('configure seo settings'),
    'file' => 'ding_seo.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function ding_seo_permission() {
  return array(
    'configure seo' => array(
      'title' => t('Configure SEO settings'),
      'description' => t('Configure settings of the SEO module'),
    ),
  );
}
